#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PIL import Image


def create_image(mode, size, cb):
    """
    Create an image with given color `mode` and `size`,
    each pixel is generated by passing the row coordinate x
    and column coordinate y to the callback.
    """
    # create a new image
    out = Image.new(mode, size)
    width, height = size
    # draw the new image
    data = [cb(x, y) for y in range(height) for x in range(width)]
    out.putdata(data)
    return out
